name: Generate PT Category Rules

on:
  schedule:
    - cron: '0 0 1 * *'   # 每周运行
  workflow_dispatch:      # 允许手动触发

jobs:
  generate:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set variables
        run: |
          # Tracker 域名列表
          echo "TRACKER_URL=https://raw.githubusercontent.com/NasPilot/domains/refs/heads/domains/Tracker.list" >> $GITHUB_ENV
          echo "PRIVATE_TRACKER_URL=https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/PrivateTracker/PrivateTracker.list" >> $GITHUB_ENV
          echo "TRACKERS_COLLECTION_URL=https://gitea.com/XIU2/TrackersListCollection/raw/branch/master/all.txt" >> $GITHUB_ENV

      - name: Generate PT category rule-set
        env:
          SED: sed '/^\s*#/d' | sed 's/DOMAIN,/full:/g' | sed 's/DOMAIN-SUFFIX,//g' | sed 's/DOMAIN-KEYWORD,/keyword:/g' | sed '/^\s*IP-CIDR/d'
        run: |
          mkdir -p rules
          # 合并所有 tracker 来源
          curl -sSL "$TRACKER_URL" | ${{ env.SED }} > rules/tracker-temp.txt
          curl -sSL "$PRIVATE_TRACKER_URL" | ${{ env.SED }} >> rules/tracker-temp.txt
          curl -sSL "$TRACKERS_COLLECTION_URL" | grep -i "\.[A-Z]" | grep -v tracker | sed 's/^.*\/\///g' | sed 's/:.*\/.*//g' >> rules/tracker-temp.txt
          sort -u rules/tracker-temp.txt -o rules/tracker-temp.txt  # 去重排序

          sed '/^\s*#/d' | \
          sed 's/DOMAIN-SUFFIX,//g' | \
          sort -u | \
          awk 'BEGIN {
              print "{"
              print "  \"version\": 1,"
              print "  \"rules\": ["
              print "    {"
              print "      \"domain_suffix\": ["
          }
          NR==1 {
              printf "        \"%s\"", $0
          }
          NR>1 {
              printf ",\n        \"%s\"", $0
          }
          END {
              print "\n      ]"
              print "    }"
              print "  ]"
              print "}"
          }' > rules/category-pt.json
          sing-box rule-set compile rules/category-pt.json -o rules/category-pt.srs

      - name: Checkout sing branch
        run: |
          git fetch
          git checkout sing
          mkdir -p geo/geosite
          mv rules/category-pt.srs geo/geosite/
          
      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add geo/geosite/category-pt.srs
          git commit -m "Update PT category rules" || exit 0
          git push origin sing
